import { Link } from 'react-router-dom';
import '../styles/Legal.css';

const TermsPage = () => {
  return (
    <div className="legal-page">
      <div className="legal-container">
        <div className="legal-header">
          <h1>Terms & Conditions</h1>
          <p className="legal-updated">Last updated: August 18, 2026</p>
        </div>

        <div className="legal-content">
          <section className="legal-section">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Vision2Venture platform ("Service"), you agree to be bound by these 
              Terms and Conditions ("Terms"). If you do not agree to all of these Terms, you must not access 
              or use the Service. These Terms apply to all visitors, users, and others who access or use the Service.
            </p>
          </section>

          <section className="legal-section">
            <h2>2. Description of Service</h2>
            <p>
              Vision2Venture is an AI-powered startup analysis platform that provides automated business 
              assessments, market analysis, competitor evaluation, financial projections, risk scoring, and 
              other analytical reports for startup ideas submitted by users.
            </p>
          </section>

          <section className="legal-section important-notice">
            <h2>3. AI-Generated Content Disclaimer</h2>
            <div className="disclaimer-box">
              <span className="disclaimer-icon">⚠️</span>
              <div>
                <p><strong>Important:</strong> All analyses, scores, projections, and recommendations provided 
                by Vision2Venture are generated by artificial intelligence (AI) and machine learning models. 
                These outputs are <strong>not guaranteed to be accurate, complete, or error-free</strong>.</p>
                <ul>
                  <li>AI-generated content may contain <strong>inaccuracies, factual errors, or misleading information</strong>.</li>
                  <li>Market data, competitor information, and financial projections are <strong>estimates based on AI predictions</strong> and may not reflect real-world conditions.</li>
                  <li>Risk scores and viability assessments are <strong>algorithmic approximations</strong> and should not be treated as professional financial, legal, or business advice.</li>
                  <li>The AI chatbot assistant may occasionally produce <strong>incorrect or outdated responses</strong>.</li>
                  <li>Generated PDF reports are <strong>automated summaries</strong> and should be independently verified before making any business decisions.</li>
                </ul>
              </div>
            </div>
            <p>
              <strong>You acknowledge and agree that you will not rely solely on AI-generated analysis 
              from this platform for making business, financial, or investment decisions.</strong> Always 
              consult qualified professionals — including financial advisors, legal counsel, and industry 
              experts — before acting on any information provided by this Service.
            </p>
          </section>

          <section className="legal-section">
            <h2>4. No Professional Advice</h2>
            <p>
              The Service does not provide professional business, financial, investment, legal, or tax advice. 
              All content is for <strong>informational and educational purposes only</strong>. Vision2Venture 
              is not a substitute for consultation with qualified professionals who can assess your specific 
              situation and needs.
            </p>
          </section>

          <section className="legal-section">
            <h2>5. User Accounts</h2>
            <p>
              When you create an account, you are responsible for maintaining the security of your account 
              credentials and for all activities that occur under your account. You must:
            </p>
            <ul>
              <li>Provide accurate and complete registration information.</li>
              <li>Keep your password confidential and secure.</li>
              <li>Notify us immediately of any unauthorized access to your account.</li>
              <li>Not share your account credentials with third parties.</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>6. User Content & Data</h2>
            <p>
              By submitting startup ideas, business descriptions, and other information to the Service, you:
            </p>
            <ul>
              <li>Retain full ownership of your intellectual property and ideas.</li>
              <li>Grant Vision2Venture a limited license to process your data solely for generating analysis reports.</li>
              <li>Acknowledge that your submitted data may be processed by third-party AI services (including but not limited to NVIDIA, Groq, and Google) for analysis purposes.</li>
              <li>Understand that while we take reasonable measures to protect your data, no method of electronic storage is 100% secure.</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>7. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Submit illegal, fraudulent, or deceptive business ideas.</li>
              <li>Attempt to reverse-engineer, hack, or disrupt the platform.</li>
              <li>Scrape, harvest, or bulk-download content or data from the Service.</li>
              <li>Impersonate another person or entity.</li>
              <li>Violate any applicable local, national, or international law.</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, Vision2Venture and its creators, 
              contributors, and affiliates shall <strong>not be liable</strong> for any indirect, 
              incidental, special, consequential, or punitive damages — including but not limited to 
              loss of profits, data, or business opportunities — arising out of or related to your 
              use of the Service, whether based on warranty, contract, tort, or any other legal theory.
            </p>
            <p>
              In particular, Vision2Venture shall <strong>not be held responsible</strong> for any 
              business decisions, investments, or actions taken based on AI-generated analysis, scores, 
              or recommendations provided by this platform.
            </p>
          </section>

          <section className="legal-section">
            <h2>9. Service Availability</h2>
            <p>
              Vision2Venture is provided on an "as is" and "as available" basis. We do not guarantee 
              that the Service will be uninterrupted, timely, secure, or error-free. The platform is 
              hosted on free-tier cloud infrastructure and may experience:
            </p>
            <ul>
              <li>Temporary downtime or slow response times due to server cold starts.</li>
              <li>Service interruptions during maintenance or updates.</li>
              <li>Rate limiting on AI API calls during periods of high demand.</li>
            </ul>
          </section>

          <section className="legal-section">
            <h2>10. Modifications to Terms</h2>
            <p>
              We reserve the right to modify or replace these Terms at any time. Material changes will 
              be communicated through the platform. Your continued use of the Service after any changes 
              constitutes acceptance of the new Terms.
            </p>
          </section>

          <section className="legal-section">
            <h2>11. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Service immediately, without 
              prior notice, if you breach these Terms. Upon termination, your right to use the Service 
              will cease immediately.
            </p>
          </section>

          <section className="legal-section">
            <h2>12. Contact Information</h2>
            <p>
              If you have any questions about these Terms & Conditions, please contact us at:
            </p>
            <p className="contact-email">
              📧 <a href="mailto:devendrababumotupalli@gmail.com">devendrababumotupalli@gmail.com</a>
            </p>
          </section>
        </div>

        <div className="legal-footer-nav">
          <Link to="/privacy-policy">Privacy Policy</Link>
          <Link to="/">Back to Home</Link>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
